let title = 'Оценка работы разработчика';
let screens = 'Простые, Сложные, Интерактивные';
let screenPrice = 1000;
screens = screens.toLowerCase().split(', ');
let rollback = 25;
let fullPrice = 2000;
let adaptive = true;
let percent = fullPrice * (rollback/100);
console.log(typeof title);
console.log(typeof fullPrice);
console.log(typeof adaptive);
console.log(screens.length);
console.log('Стоимость верстки экранов ' + screenPrice + ' рублей/ долларов/гривен/юани');
console.log('Стоимость разработки сайта ' + fullPrice + ' рублей/ долларов/гривен/юани');
console.log(screens);
console.log(percent);
